// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go

// Package mock_urlshortenerservice is a generated GoMock package.
package mock_urlshortenerservice

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAliasGenerator is a mock of AliasGenerator interface.
type MockAliasGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockAliasGeneratorMockRecorder
}

// MockAliasGeneratorMockRecorder is the mock recorder for MockAliasGenerator.
type MockAliasGeneratorMockRecorder struct {
	mock *MockAliasGenerator
}

// NewMockAliasGenerator creates a new mock instance.
func NewMockAliasGenerator(ctrl *gomock.Controller) *MockAliasGenerator {
	mock := &MockAliasGenerator{ctrl: ctrl}
	mock.recorder = &MockAliasGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAliasGenerator) EXPECT() *MockAliasGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAliasGenerator) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAliasGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAliasGenerator)(nil).Generate))
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetLongURL mocks base method.
func (m *MockStorage) GetLongURL(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongURL", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLongURL indicates an expected call of GetLongURL.
func (mr *MockStorageMockRecorder) GetLongURL(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongURL", reflect.TypeOf((*MockStorage)(nil).GetLongURL), ctx, alias)
}

// SaveURL mocks base method.
func (m *MockStorage) SaveURL(ctx context.Context, url, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, url, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockStorageMockRecorder) SaveURL(ctx, url, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockStorage)(nil).SaveURL), ctx, url, alias)
}
